# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SSE_Dome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSE_Dome
 
 pod 'Moya/RxSwift', '~> 15.0'
 pod 'RxSwift'
 pod 'RxCocoa', '~>6.0'

  
  target 'SSE_DomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SSE_DomeUITests' do
    # Pods for testing
  end

end
